name: Devops lab workflow

on:
  workflow_dispatch:

jobs:
  echo-steps:
    runs-on: ubuntu-latest

    steps:
      -name: fisrt step
      run: echo"this is the fisrt step"background: 

      -name: second step
      run: echo"this is the second step"
